### ISSUE TITLE
[GMYC-tutorial]

### ISSUE THREAD

**Issue by reeb** [fmichonneau/francoismichonneau.net#23]
Merci beaucoup pour ce tutorial! Génial.
C Reeb

**Comment by fmichonneau** [comment]
Pas de problème ! Je suis content qu'il t'ait été utile.

**Comment by Taufan2022** [comment]
i can't running in this section : Summarizing the posterior with treeannotator
difference software treeannotator. You write use coding, but in treeannotator (i downloading from your website) can't use coding.
