### ISSUE TITLE
[GMYC-tutorial]

### ISSUE THREAD

**Issue by msheidai** [fmichonneau/francoismichonneau.net#32]
Hi there,
I tried several different approaches to. downloads splits package for. r, through R-STUDIO, but was not. friutfuul Please kindly help in this regard. 

Thanks 
msheidai

**Comment by msheidai** [comment]
I tried for Mac pro

**Comment by fmichonneau** [comment]
Try with `install.packages("splits", repos="http://R-Forge.R-project.org")`

**Comment by msheidai** [comment]
Dear. Sir, 
This is the result after trying install.packages("splits", repos="http://R-Forge.R-project.org"):

[Result.pdf](https://github.com/fmichonneau/francoismichonneau.net/files/5818144/Result.pdf)

**Comment by fmichonneau** [comment]
it looks like you don't have the developer tools installed to be able to install this package. You may want to look into `brew` (https://brew.sh/) which I think will install the tools you need. After installing brew, try to reinstall the package from R. If that still doesn't work, I suggest you contact the authors of the `splits` package.
